Models/ErrorViewModel.cs
namespace Wingineers.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Order.cs
public class Order{
    public int Id {get; set;}
    public string? OrderName{get; set;}
    public double OrderPrice{get; set;}
    public string? OrderDate{get; set;}
    public int SalesPersonId{get; set;}
}

Models/SalesPerson.cs
using Microsoft.AspNetCore.SignalR;

public class SalesPerson{
    public int Id {get; set;}
    public string? Name{get; set;}
    public string? HireDate{get; set;}
    public string? Address{get; set;}
    public string? City{get; set;}
    public string? ZipCode{get; set;}
    public IEnumerable<Order>? Orders {get; set;}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Wingineers.Models;

namespace Wingineers.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/OrdersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Globalization;

namespace Wingineers.Controllers;

public class OrdersController : Controller
{
    private readonly HttpClient _httpClient;

    public OrdersController(){
        _httpClient = new HttpClient();
    }
    
    public async Task<IEnumerable<Order>> GetOrders(){
        string baseUrl = "https://azurecandidatetestapi.azurewebsites.net/api/v1";
        string endpointPath = "/Orderlines"; 
        string apiUrl = $"{baseUrl}{endpointPath}";

        string apiKey = "test1234";
        _httpClient.DefaultRequestHeaders.Add("ApiKey", apiKey);

    
        HttpResponseMessage response = await _httpClient.GetAsync(apiUrl);
        if (response.IsSuccessStatusCode){
            //HttpResponseMessage -> string
            string responseContent = await response.Content.ReadAsStringAsync();
            
            // Process the response content and pass data to a list
            IEnumerable<Order> orders = new List<Order>();
            orders =  JsonConvert.DeserializeObject<IEnumerable<Order>>(responseContent);
            return orders;
        }else{
            Console.WriteLine("No successful status code when retrieving API");
            return null;
        }
    }

    public async Task<ActionResult> Orders(){
        //All orders
        var orders = await GetOrders();

        //The different formats a date can be represented in
        string[] formats = { "dd-MM-yyyy HH:mm", "yyyy-MM-dd HH:mm" };

        //Dictionary for storing months and amount of orders to use for graph
        IDictionary<string, int> dictOrders = new Dictionary<string, int>();

        //Predefine the dictionary with every month 
        for (int i = 43; i >= 0; i--) {
            DateTime dateTime = DateTime.Now.AddMonths(-i);
            string shortDate = dateTime.Month.ToString("d2") + "/" + dateTime.Year.ToString();
            dictOrders.Add(shortDate,0);
        }

        //Adding the amount of orders on each month
        foreach (Order order in orders){
            DateTime dateTime;
            if (DateTime.TryParseExact(order.OrderDate, formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out dateTime)){
                string shortDate = dateTime.Month.ToString("d2") + "/" + dateTime.Year.ToString();
                dictOrders[shortDate] = dictOrders[shortDate] + 1;
            }else{
                Console.WriteLine("Unable to parse DateTime");
            }
        }
        //Returning the dictionary to ordersView så the graph can be shown
        return View("OrdersView",dictOrders);
    }  
}

Controllers/SalesPersonController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;


namespace Wingineers.Controllers;

public class SalesPersonController : Controller
{
    private readonly HttpClient _httpClient;
    public List<SalesPerson> salesPeople;

    public SalesPersonController(){
        _httpClient = new HttpClient();
    }
    
    public async Task<List<SalesPerson>> GetSalesPeople(){
        string baseUrl = "https://azurecandidatetestapi.azurewebsites.net/api/v1";
        string endpointPath = "/SalesPersons"; 
        string apiUrl = $"{baseUrl}{endpointPath}";

        string apiKey = "test1234";
        _httpClient.DefaultRequestHeaders.Add("ApiKey", apiKey);

        HttpResponseMessage response = await _httpClient.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode){
            string responseContent = await response.Content.ReadAsStringAsync();
            // Process the response content and pass data to the view
            salesPeople =  JsonConvert.DeserializeObject<List<SalesPerson>>(responseContent);

            OrdersController ordersController = new();
            var orders = await ordersController.GetOrders();

            //Adding orders to each salesperson
            foreach (var salesPerson in salesPeople){
                salesPerson.Orders = orders.Where( x => x.SalesPersonId == salesPerson.Id).ToList();
            }
            return salesPeople;
        }
        else{
            return null;
        }
    }

    public async Task<ActionResult> SalesPeople(){
        var salesPeople = await GetSalesPeople();
        return View("SalesPersonView",salesPeople);
    } 

    public async Task<ActionResult> GetDetails(int salespersonid){
            IEnumerable<SalesPerson> salesPeople = await GetSalesPeople();
            //Get the salesperson with the same id
            var person = salesPeople.FirstOrDefault(x => x.Id == salespersonid);
            return View("SalesPersonDetailView", person);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Wingeneers</h1>
</div>

Views/Orders/OrdersView.cshtml
@model Dictionary<string, int>
@{
    ViewBag.Title = "Orders Overview";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
</head>
<body>
    <canvas id="columnChart" width="400" height="300"></canvas>

    <script>
        var chartData = @Html.Raw(Json.Serialize(Model));

        var ctx = document.getElementById('columnChart').getContext('2d');
        var columnChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: Object.keys(chartData),
                datasets: [{
                    label: 'Amount of orders',
                    data: Object.values(chartData),
                    backgroundColor: '#5166d0',
                    borderColor: '#0625bc',
                    borderWidth: 2,
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
</body>
</html>

Views/SalesPerson/SalesPersonDetailView.cshtml
@model SalesPerson

<!DOCTYPE html>
<html>
<head>
    <title>Sales Person Details</title>
</head>
<body>
    <h2>@Model.Name</h2>
    <p>Id: @Model.Id </p>
    <p>Hire date: @Model.HireDate</p>
    <p>Address: @Model.Address</p>
    <p>City: @Model.City</p>
    <p>Zip Code: @Model.ZipCode</p>
    <table class="styled-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Order Date</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var order in @Model.Orders)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.OrderName</td>
                <td>@order.OrderPrice</td>
                <td>@order.OrderDate.Substring(0,10)</td>
            </tr>
        }
        </tbody>
    </table>
</body>
</html>

Views/SalesPerson/SalesPersonView.cshtml
@model List<SalesPerson>

<!DOCTYPE html>
<html>
<head>
    <title>Sales People Table</title>
</head>
<body>
    <h2>Sales people</h2>
    <table class="styled-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Orders</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var salesPerson in Model)
        {
            <tr>
                <td>@salesPerson.Id</td>
                <td>@salesPerson.Name</td>
                <td>@salesPerson.Orders.Count()</td>
                <td><a asp-area="" asp-controller="SalesPerson" asp-action="GetDetails" asp-route-salespersonid=@salesPerson.Id><button>Details</button></a></td>
            </tr>
        }
        </tbody>
    </table>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wingineers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Wingineers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wingineers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesPerson" asp-action="SalesPeople">Sales People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Orders">Order Overview</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Wingineers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>